name: Submit Solution
description: Upload your zip file to submit your code.
body:
  - type: dropdown
    id: question_id
    attributes:
      label: Question Selection
      options:
        - "Q1: Target Sum Matcher"
        - "Q2: Bubble Sort"
    validations:
      required: true
  - type: textarea
    id: zip_upload
    attributes:
      label: Upload ZIP File
      description: Drag and drop your project ZIP file here.
    validations:
      required: true
