name: Submit Solution
description: Upload your zip file to submit your code.
body:
  - type: dropdown
    id: question_id
    attributes:
      label: Question Selection
      options:
        - "Q1: Target Sum Matcher"
        - "Q2: Bubble Sort"
        - "Q3: Double Trouble"
        - "Q4: Insertion Sort"
        - "Q5: Longest Increasing Subsequence"
        - "Q6: Valid Parentheses"
        - "Q7: Binary Search"
        - "Q8: Reverse a Linked List"
        - "Q9: GCD via Recursion"
        - "Q10: First Non-Repeating Character"
    validations:
      required: true
  - type: textarea
    id: zip_upload
    attributes:
      label: Upload ZIP File
      description: Drag and drop your project ZIP file here.
    validations:
      required: true
